import "./globals.css";
import { Montserrat } from "next/font/google";

// const montserrat = Montserrat({
//   weight: ["400", "700"],
//   subsets: ["latin"],
//   variable: "--font-montserrat",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`max-w-full mx-auto`}>
        <nav className="font-bold flex justify-between items-center p-8">
          <h1>logo</h1>
          <ul>
            <li>
              <a href="/about">About</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
